### ISSUE TITLE
Information on how to compile locally

### ISSUE THREAD

**Issue by KyleStiers** [ExcitedStates/qfit#2]
Hello, I was wondering if it would be possible to get some information on how to build this locally. 

I see that looptk and a few other things are required from the Makefile, but is everything here that is necessary to build and run qFit 2.0 locally? I have many data-sets that I would like to run, and am unsure of if the webserver (smb.slac.stanford.edu/qFitServer/) implements qFit 2.0 or not.

If someone could just say go install packages x,y,z, and then run configure, make, install etc that would be really helpful.

Thanks.

P.S. Are run times feasible on a single machine or is a cluster really necessary?

**Comment by latrocinia** [comment]
Hi Kyle,

Unfortunately installing this qFit is not straightforward. Currently we are porting and upgrading this package to a Python stack, which will allow easy installation and improved performance. So for now, we strongly recommend using the server, though Henry mentioned giving you access to his cluster, please follow up with him if you prefer.

If you still want to give it a try, you will first need to install the following:
* MMDB (with the GPP4 library, a CCP4 library standin)
* FFTW
* Clipper
* GSL
* libxml2 (usually already present)
* LoopTK
* boost
* CGAL
* CPLEX

Simplifying the installation of this qFit repo is not a priority for us, as all effort is in moving towards qFit3.

We recommend performing calculations on a cluster with this version.

Best,
Gydo

**Comment by KyleStiers** [comment]
Thanks for the information Gydo. I'm looking forward to qFit 3.0!
